name = "glubsub"
version = "1.2.0"

description = "A simple PubSub library using Gleam actors"
licences = ["Apache-2.0"]
repository = { type = "github", user = "okkdev", repo = "glubsub" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
